# Generated by Django 4.0.4 on 2022-06-10 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=50)),
                ('designation_name', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=50)),
                ('reporting_to', models.CharField(max_length=50)),
                ('department_head', models.CharField(max_length=80)),
                ('shiftid', models.CharField(choices=[('ap', 'APAC'), ('uk', 'UK')], default='UK', max_length=6)),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
