# Generated by Django 4.0.4 on 2022-05-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedashboard', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location_name',
            field=models.CharField(default='Cbe', max_length=50),
            preserve_default=False,
        ),
    ]
