# Generated by Django 3.2.8 on 2022-05-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('floor_number', models.CharField(choices=[('1', 'One'), ('2', 'Two')], max_length=6)),
                ('tower_id', models.CharField(choices=[('A', 'Tower A'), ('B', 'Tower B')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('oc', 'Occupied'), ('un', 'Unoccupied'), ('bu', 'Buffer')], max_length=6)),
                ('shiftid', models.CharField(choices=[('ap', 'APAC'), ('uk', 'UK')], max_length=6)),
            ],
        ),
    ]
