# Generated by Django 3.2.8 on 2022-05-15 11:20

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='id',
        ),
        migrations.AddField(
            model_name='seats',
            name='kmm',
            field=models.CharField(default='not assigned', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=django.db.models.functions.text.Concat('seat_number', 'floor_number', 'tower_id')),
        ),
    ]
