# Generated by Django 3.2.8 on 2022-05-15 11:21

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_auto_20220515_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='kmm',
            field=models.CharField(default='not assigned', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=django.db.models.functions.text.Concat('seat_number', 'floor_number', 'tower_id', 'ShiftField.shiftid')),
        ),
    ]
