# Generated by Django 3.2.8 on 2022-05-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0003_alter_seats_kmm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='kmm',
            new_name='key',
        ),
    ]
