# Generated by Django 3.2.8 on 2022-05-15 11:44

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0004_rename_kmm_seats_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftField',
        ),
        migrations.AddField(
            model_name='seats',
            name='shiftid',
            field=models.CharField(choices=[('ap', 'APAC'), ('uk', 'UK')], default='UK', max_length=6),
        ),
        migrations.AddField(
            model_name='seats',
            name='state',
            field=models.CharField(choices=[('oc', 'Occupied'), ('un', 'Unoccupied'), ('bu', 'Buffer')], default='Unoccupied', max_length=6),
        ),
        migrations.AlterField(
            model_name='seats',
            name='key',
            field=models.CharField(default=django.db.models.functions.text.Concat('seat_number', 'floor_number', 'tower_id', 'ShiftField.shiftid'), max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
