# Generated by Django 3.2.8 on 2022-05-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0005_auto_20220515_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='key',
        ),
        migrations.AddField(
            model_name='seats',
            name='auto_increment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
