# Generated by Django 3.2.8 on 2022-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0006_auto_20220515_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_number', models.IntegerField()),
                ('floor_number', models.CharField(choices=[('1', 'One'), ('2', 'Two')], max_length=6)),
                ('tower_id', models.CharField(choices=[('A', 'Tower A'), ('B', 'Tower B')], max_length=6)),
                ('state', models.CharField(choices=[('oc', 'Occupied'), ('un', 'Unoccupied'), ('bu', 'Buffer')], default='Unoccupied', max_length=6)),
                ('shiftid', models.CharField(choices=[('ap', 'APAC'), ('uk', 'UK')], default='UK', max_length=6)),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Seats',
        ),
    ]
