# Generated by Django 3.2.8 on 2022-05-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('lh_name', models.CharField(max_length=50)),
                ('lh_id', models.CharField(max_length=50)),
                ('dh_name', models.CharField(max_length=50)),
                ('dh_id', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
