# Generated by Django 3.2.8 on 2022-05-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_realloc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requests',
            new_name='request',
        ),
    ]
