# Generated by Django 3.2.8 on 2022-05-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_realloc', '0002_rename_requests_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='rel_request',
        ),
    ]
