# Generated by Django 3.2.8 on 2022-05-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_realloc', '0003_rename_request_rel_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rel_request',
            name='reason',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
