# Generated by Django 3.2.8 on 2022-05-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_realloc', '0004_alter_rel_request_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='rel_request',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='rel_request',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
