# Generated by Django 3.2.8 on 2022-05-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_realloc', '0005_auto_20220522_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rel_request',
            name='id',
        ),
        migrations.AlterField(
            model_name='rel_request',
            name='request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
